package com.lcwd.rating.entity;





import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
//in order to convert it into the object in jpa we used entity but here we will use @Document
@Document("user_ratings")
public class Rating {
	
	//in mongodb id are already autogenerated
	@Id
	private Integer id;
	private Integer userId;
	private Integer hotelId;
	private int rating;
	private String feedback;
	private Date addedTime;
	
	

}
